# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/pathakadithi/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

In [3]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 1. Unit of analysis + time window

The warehouse fact table `fact_content_query_90d` is at a **content × query × 90-day window** grain. A row is identified by `content_hash_id`, `query_hash_id`, `window_start`, and `window_end`.

For the Refresh / Content Opportunity Scoring lane, the eventual decision unit is the **content item/page**. Therefore, query-level records will need to be aggregated to the content level before scoring pages.

I will use **March 2026 (`month = 2026-03`)** as the development and verification window and keep the final June 2026 month sealed as the natural outcome/test period.v

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

In [4]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 2. Fields: feature / label / context / excluded

### Features

The features I plan to use are:

- `impressions_90d` — recent search exposure available before the refresh decision.
- `clicks_90d` — recent click performance available before the decision.
- `ctr` — observed click-through performance available before the decision.
- `avg_position` — search ranking information available before the decision.
- `days_since_last_update` — freshness information available before the decision.

### Label / proxy

- **Refresh opportunity proxy** — a proxy representing the potential value of refreshing a page. The ideal label would be the improvement in performance after a refresh, but the current warehouse data does not directly provide that post-refresh outcome.

### Context

These fields can provide useful context about the page or help analyze segments, but I will not use them as model features in the five-feature frame:

- `content_id` — identifies the content item.
- `client_id` — identifies the client/account.
- `content_type` — describes the type of content.
- `main_intent` — describes the search intent.
- `competition_level` — describes the competitive environment.
- `age_tier` — groups content by age.
- `freshness_tier` — groups content by freshness.
- `trend_direction` — describes the current performance trend.

### Excluded

- `impressions_last_30d`, `clicks_last_30d`, and `sessions_last_30d` from a future/outcome period will be excluded when they are not available at the decision moment.
- Any future-month performance fields will be excluded because they contain information that would only be known after the refresh decision and could cause label leakage.
- Any field directly constructed from the future outcome/label will also be excluded for the same reason.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [5]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

In [6]:
from google.colab import userdata
import os

HF_TOKEN = userdata.get("HF_TOKEN")

print("HF token loaded:", HF_TOKEN is not None)

HF token loaded: True

In [7]:
from datasets import load_dataset

query_90d = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_query_90d",
    token=HF_TOKEN
)

print(query_90d)

README.md:   0%|          | 0.00/3.04k [00:00<?, ?B/s]

fact_content_query_90d.parquet: reconstructing file:   0%|          |  0.00B / 60.7MB

fact_content_query_90d.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/2414248 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['client_hash_id', 'content_hash_id', 'query_hash_id', 'query_char_count', 'query_token_count', 'window_start', 'window_end', 'impressions_90d', 'clicks_90d', 'impressions_last30', 'clicks_last30', 'impressions_prev30', 'clicks_prev30', 'avg_position_90d', 'avg_position_last30', 'avg_position_prev30', 'content_total_impressions_90d', 'content_visible_query_count', 'rare_query_count', 'rare_impressions_share', 'anonymized_impressions_share'],
        num_rows: 2414248
    })
})

In [8]:
daily_perf = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    token=HF_TOKEN
)

print(daily_perf)

Resolving data files:   0%|          | 0/18 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/18 [00:00<?, ?files/s]

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 19.6kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 1.45MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  124MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.29MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 21.6MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 2.62MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 72.0MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  624kB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 3.22MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  134MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 4.41MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 8.93MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 7.12MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 89.0MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 90.3MB

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B / 86.2MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  149MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

fact_content_daily_performance/month=202(…): reconstructing file:   0%|          |  0.00B /  146MB

fact_content_daily_performance/month=202(…): downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/78835655 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/39 [00:00<?, ?it/s]

DatasetDict({
    train: Dataset({
        features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
        num_rows: 78835655
    })
})

In [9]:
print(daily_perf["train"].column_names)

['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

In [10]:
daily_train = daily_perf["train"]

print("Total rows:", daily_train.num_rows)
print("Columns:", daily_train.column_names)

Total rows: 78835655
Columns: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

In [11]:
query_train = query_90d["train"]

print("Total rows:", query_train.num_rows)
print("Columns:", query_train.column_names)

Total rows: 2414248
Columns: ['client_hash_id', 'content_hash_id', 'query_hash_id', 'query_char_count', 'query_token_count', 'window_start', 'window_end', 'impressions_90d', 'clicks_90d', 'impressions_last30', 'clicks_last30', 'impressions_prev30', 'clicks_prev30', 'avg_position_90d', 'avg_position_last30', 'avg_position_prev30', 'content_total_impressions_90d', 'content_visible_query_count', 'rare_query_count', 'rare_impressions_share', 'anonymized_impressions_share']

In [12]:
print(query_90d["train"].column_names)

['client_hash_id', 'content_hash_id', 'query_hash_id', 'query_char_count', 'query_token_count', 'window_start', 'window_end', 'impressions_90d', 'clicks_90d', 'impressions_last30', 'clicks_last30', 'impressions_prev30', 'clicks_prev30', 'avg_position_90d', 'avg_position_last30', 'avg_position_prev30', 'content_total_impressions_90d', 'content_visible_query_count', 'rare_query_count', 'rare_impressions_share', 'anonymized_impressions_share']

In [13]:
# Query 1 — Verify the grain
sample = query_train.select(range(1000)).to_pandas()

grain_cols = [
    "client_hash_id",
    "content_hash_id",
    "query_hash_id",
    "window_start",
    "window_end"
]

print("Rows checked:", len(sample))
print("Unique grain keys:", sample[grain_cols].drop_duplicates().shape[0])
print("Duplicate grain keys:",
      len(sample) - sample[grain_cols].drop_duplicates().shape[0])

sample[grain_cols].head(10)

Rows checked: 1000
Unique grain keys: 1000
Duplicate grain keys: 0

,client_hash_id,content_hash_id,query_hash_id,window_start,window_end
0,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_58b1b001f839d699,2026-04-02,2026-06-30
1,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_922b8eca2a24cd34,2026-04-02,2026-06-30
2,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_9f0c36a6ae2a6a99,2026-04-02,2026-06-30
3,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_a032820b5467e996,2026-04-02,2026-06-30
4,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_ba1a2f131961c5da,2026-04-02,2026-06-30
5,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_bf21a07e311fed62,2026-04-02,2026-06-30
6,client_08a6a72ff48e62c0,content_447894f2faf0d2bc,query_c9de7d945a73e134,2026-04-02,2026-06-30
7,client_08a6a72ff48e62c0,content_447b93d5ff670356,query_9dfad337ed50a6f9,2026-04-02,2026-06-30
8,client_08a6a72ff48e62c0,content_447b93d5ff670356,query_ba4af1d8841d0c41,2026-04-02,2026-06-30
9,client_08a6a72ff48e62c0,content_4483e354a2992497,query_0f5dc12980d1d9b9,2026-04-02,2026-06-30

**Grain verification:** The checked rows have a unique combination of `client_hash_id`, `content_hash_id`, `query_hash_id`, `window_start`, and `window_end`. This confirms that `fact_content_query_90d` is at the content × query × 90-day-window grain, rather than one row per content page.

In [14]:
# Query 2

march_perf = load_dataset(
    "FlyRank/internship-warehouse",
    "fact_content_daily_performance",
    data_files={"train": "fact_content_daily_performance/month=2026-03/*.parquet"},
    token=HF_TOKEN
)

print(march_perf)

Generating train split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events'],
        num_rows: 9841378
    })
})

In [15]:
# Query 2 — March 2026 row count and date span

march_df = march_perf["train"].select_columns(
    ["report_date"]
).to_pandas()

print("March 2026 row count:", len(march_df))
print("Date span:", march_df["report_date"].min(), "to",
      march_df["report_date"].max())
print("Unique dates:", march_df["report_date"].nunique())

March 2026 row count: 9841378
Date span: 2026-03-01 to 2026-03-31
Unique dates: 31

In [19]:
# Prepare March 2026 training data for Query 3
march_train = march_perf["train"]

print("March train rows:", march_train.num_rows)

March train rows: 9841378

**Query 2 result:** The March 2026 slice contains the number of daily content records shown above and covers the observed date range shown above. This verifies the size and time span of the development window using the warehouse data.

In [20]:
# Query 3 — Availability using explicit True values


availability_df = march_train.select_columns(
    ["gsc_data_available", "ga4_data_available"]
).to_pandas()

total_rows = len(availability_df)

available_rows = (
    (availability_df["gsc_data_available"] == True) &
    (availability_df["ga4_data_available"] == True)
).sum()

print("March 2026 rows:", total_rows)
print("Rows with GSC AND GA4 available:", available_rows)
print("Rows surviving availability filter:", available_rows)

March 2026 rows: 9841378
Rows with GSC AND GA4 available: 364347
Rows surviving availability filter: 364347

**Query 3 result:** I explicitly require both GSC and GA4 data to be available. Only rows where both availability fields are `True` survive the availability filter. This prevents unavailable data from entering the feature-building stage.

Five-feature frame

I use five features that are available before the refresh decision: impressions_90d, clicks_90d, ctr, avg_position, and days_since_last_update. These describe recent exposure, clicks, click-through performance, search position, and content freshness.

In [22]:
query_train = query_90d["train"]

In [23]:
# Inspect the 90-day query table columns for the five-feature frame

print("Available columns in fact_content_query_90d:")
print(query_train.column_names)

Available columns in fact_content_query_90d:
['client_hash_id', 'content_hash_id', 'query_hash_id', 'query_char_count', 'query_token_count', 'window_start', 'window_end', 'impressions_90d', 'clicks_90d', 'impressions_last30', 'clicks_last30', 'impressions_prev30', 'clicks_prev30', 'avg_position_90d', 'avg_position_last30', 'avg_position_prev30', 'content_total_impressions_90d', 'content_visible_query_count', 'rare_query_count', 'rare_impressions_share', 'anonymized_impressions_share']

In [24]:
# Check columns available in the daily performance table
print(daily_train.column_names)

['report_date', 'client_hash_id', 'content_hash_id', 'client_has_gsc', 'client_has_ga4', 'gsc_data_available', 'ga4_data_available', 'gsc_impressions', 'gsc_clicks', 'gsc_sum_position', 'gsc_avg_position', 'ga4_pageviews', 'ga4_sessions', 'ga4_users', 'ga4_engaged_sessions', 'ga4_total_engagement_sec', 'sessions_organic', 'sessions_direct', 'sessions_referral', 'sessions_social', 'sessions_paid', 'sessions_ai', 'ai_chatgpt', 'ai_perplexity', 'ai_gemini', 'ai_copilot', 'ai_claude', 'ai_meta', 'ai_other', 'scroll_events']

In [25]:
# Build the five-feature frame from the 90-day query table

feature_df = query_train.select_columns([
    "impressions_90d",
    "clicks_90d",
    "avg_position_90d",
    "avg_position_last30"
]).to_pandas()

# Derive CTR from historical clicks and impressions
feature_df["ctr"] = (
    feature_df["clicks_90d"] /
    feature_df["impressions_90d"].replace(0, float("nan"))
)

feature_cols = [
    "impressions_90d",
    "clicks_90d",
    "ctr",
    "avg_position_90d",
    "avg_position_last30"
]

feature_df = feature_df[feature_cols]

print("Feature frame shape:", feature_df.shape)
print("Features:", feature_df.columns.tolist())

feature_df.head()

Feature frame shape: (2414248, 5)
Features: ['impressions_90d', 'clicks_90d', 'ctr', 'avg_position_90d', 'avg_position_last30']

   impressions_90d  clicks_90d  ctr  avg_position_90d  avg_position_last30
0               11           0  0.0         10.818182                  NaN
1               13           0  0.0          1.769231                  NaN
2               16           0  0.0         23.562500            24.272727
3               55           0  0.0          2.200000            13.000000
4               14           0  0.0          3.428571                  NaN

Refresh opportunity proxy

Because the warehouse does not contain a post-refresh outcome, I use a simple historical decline proxy for this experiment. A row is marked as declining when clicks in the latest 30-day period are lower than clicks in the preceding 30-day period. This is a decision-support proxy, not evidence that a future refresh will improve performance.

In [28]:
# Refresh opportunity proxy
# 1 = recent clicks declined compared with the previous 30-day period
# 0 = otherwise

query_df = query_train.select_columns([
    "clicks_last30",
    "clicks_prev30"
]).to_pandas()

query_df["refresh_opportunity_proxy"] = (
    query_df["clicks_last30"] < query_df["clicks_prev30"]
).astype(int)

print("Proxy rows:", len(query_df))
print("Proxy distribution:")
print(query_df["refresh_opportunity_proxy"].value_counts())

Proxy rows: 2414248
Proxy distribution:
refresh_opportunity_proxy
0    2336206
1      78042
Name: count, dtype: int64

In [29]:
# Deliberate leakage experiment
# We intentionally include the label itself as a feature.

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# Use the five honest features
X_honest = feature_df.copy()

# Fill missing values
X_honest = X_honest.fillna(X_honest.median(numeric_only=True))

# Proxy label
y = query_df["refresh_opportunity_proxy"]

# Deliberately leaked feature: the label itself
X_leaky = X_honest.copy()
X_leaky["refresh_opportunity_proxy_LEAK"] = y.values

X_train, X_test, y_train, y_test = train_test_split(
    X_leaky,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

leaky_model = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

leaky_model.fit(X_train, y_train)

leaky_pred = leaky_model.predict(X_test)

print("Leaky model accuracy:", accuracy_score(y_test, leaky_pred))

Leaky model accuracy: 1.0

In [30]:
# Remove the deliberately leaked label-derived feature
X_honest = feature_df.copy()

# Fill missing numeric values using medians
X_honest = X_honest.fillna(X_honest.median(numeric_only=True))

X_train, X_test, y_train, y_test = train_test_split(
    X_honest,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

honest_model = DecisionTreeClassifier(
    max_depth=3,
    random_state=42
)

honest_model.fit(X_train, y_train)

honest_pred = honest_model.predict(X_test)

print("Honest model accuracy:", accuracy_score(y_test, honest_pred))
print("Features kept:", X_honest.columns.tolist())

Honest model accuracy: 0.9682717199958579
Features kept: ['impressions_90d', 'clicks_90d', 'ctr', 'avg_position_90d', 'avg_position_last30']

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. Data limits

This data cannot tell me with certainty whether refreshing a page will actually cause its performance to improve. The historical data is observational, so it does not provide a controlled before/after experiment for every content refresh.

There are also several limitations:

- **Unbalanced history:** Some content has more complete performance history than other content, so comparisons between pages may not be equally reliable.
- **GSC-only early rows:** Some earlier records may have GSC data available without equivalent GA4 data, which limits the completeness of engagement-based features.
- **Window overlaps:** The 90-day windows overlap across periods, so observations are not fully independent. A later window can contain much of the same historical information as an earlier window.
- **Missing causal information:** The data does not fully capture why a page performed poorly or whether a specific content change caused a later improvement.

Therefore, the model can rank pages by estimated refresh opportunity, but it cannot guarantee that a refresh will improve performance.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.